name: simple_fontellico_progress_dialog
description: A simple progress dialog with custom icons.
version: 0.0.1
homepage: https://github.com/ajomuch92/simple-fontelico-progress-dialog-flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Fontelico
      fonts:
        - asset: fonts/Fontelico.ttf
